### PR TITLE
Follow-up on #6500, don't use setExceptionPauseMode() if possible

### LINKED ISSUE #6500: Please remove usages of `setExceptionPauseMode`
That VM Service procedure is deprecated and we intend to remove it in v4.0 of the VM Service spec. Please use `setIsolatePauseMode` instead.

### PR DESCRIPTION
**Pull request by alexander-doroshko**
Fixes #6500

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
@stevemessick

**Review by stevemessick — APPROVED** [review]
Thanks!

**Comment by alexander-doroshko** [comment]
Could you push the PR for me? I seem not to have permissions. Also, not sure what failed `presubmit / checker (UNIT_TEST_BOT)` means.

**Comment by alexander-doroshko** [comment]
Signed. I think you are seeing the Merge button now.

**Pull request merged**
