### PR TITLE
replace the weberknecht websocket library with Java-WebSocket-1.4.0.jar

### PR DESCRIPTION
**Pull request by devoncarew**
- replace the weberknecht websocket library with Java-WebSocket-1.4.0.jar

This replaces the `weberknecht-0.1.5.jar` websocket library with the `Java-WebSocket-1.4.0.jar` one. The Java-WebSocket library is likely better maintained and may address some of the longer tail issues we see with weberknecht (like the issue below, where a websocket message is split at char 51604).

If we land this, we'll want to update the source `org/dartlang/vm/service/VmServiceBase.java` library in the dart-lang/sdk repo, as well as the Dart plugin.

I verified that use cases like the inspector, and source level debugging, work with this new library.

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 51604 path $.result.asyncCausalFrames[9].function.owner
  com.google.gson.internal.Streams.parse(), Streams.java:60
  com.google.gson.JsonParser.parse(), JsonParser.java:84
  com.google.gson.JsonParser.parse(), JsonParser.java:59
  com.google.gson.JsonParser.parse(), JsonParser.java:45
  org.dartlang.vm.service.VmServiceBase.processMessage(), VmServiceBase.java:412
  org.dartlang.vm.service.VmServiceBase$1.onMessage(), VmServiceBase.java:86
  de.roderick.weberknecht.WebSocketReceiver.run(), WebSocketReceiver.java:65

Parse message failed: {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@1321134198\/scripts\/p...
```

### CODE REVIEW

**Comment by devoncarew** [comment]
I'll need to update the ant script for this change.

**Comment by devoncarew** [comment]
Looks ike I still need to fix the test bot: https://travis-ci.org/flutter/flutter-intellij/builds/600244808?utm_source=github_status&utm_medium=notification.

**Comment by devoncarew** [comment]
Hmm, @stevemessick, I've added a new jar to the project (`third_party/TooTallNate/Java-WebSocket-1.4.0-with-dependencies.jar`), but am somewhat at a loss as to how to get the gradle task which compiles the test sources to use it when compiling (https://travis-ci.org/flutter/flutter-intellij/jobs/600244811#L645).

**Comment by stevemessick** [comment]
@devoncarew It looks like that jar file is available in a maven repository. I don't have specific details but the general approach is to locate the maven repo, make sure it is visible for tests in build.gradle and add a testCompile dependency. It is similar to what we did for the powermock libraries.

**Comment by devoncarew** [comment]
Thanks! I'll look at switching to that approach.

```
// https://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket
compile group: 'org.java-websocket', name: 'Java-WebSocket', version: '1.4.0'
```

People do now have a bit more setup steps locally when building the Flutter plugin due to the maven deps. There may be some tooling we could write (`./bin/plugin init-project`?) that would automate some of the currently manual steps.

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/flutter/flutter-intellij/pull/4011.

**Pull request closed without merging**
