### PR TITLE
improve the location of the reload actions in the Run menu

### PR DESCRIPTION
**Pull request by devoncarew**
- improve the location of the reload actions in the Run menu

screen shot 2017-02-22 at 2 04 38 pm

@pq @skybrian

### CODE REVIEW

**Comment by skybrian** [comment]
LGTM

Regarding the menu, I wonder if "Reload Flutter App" and "Restart Flutter App" would be clearer?

**Comment by pq** [comment]
LGTM

**Comment by devoncarew** [comment]
> Regarding the menu, I wonder if "Reload Flutter App" and "Restart Flutter App" would be clearer?

We have had a bit of user confusion in terms of the difference between hot reload and a full restart. I think `full restart` helps imply that we're doing more work than a incremental reload.

I'll land this as is, but we may want to noodle about whether these names are the ones we're happy with - that they do as much as they can to separate the two terms. /cc @johnmccutchan @mit-mit @sethladd

**Comment by skybrian** [comment]
I'd like to see "Flutter" somewhere in the menu item's name, since IDEA is also used to work on non-Flutter apps.

**Pull request merged**
