### PR TITLE
detect flutter module types in small IDEs

### PR DESCRIPTION
**Pull request by devoncarew**
- detect flutter module types in small IDEs

Re: the `<depends>` change, I believe we get the list of supported platforms from the JetBrains plugins site now - we can toggle on support for specific platforms.

@pq

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
I guess with this change auto-detection will say that the plugin is compatible with all IDEs.
If you want you can disable autodetection and select compatible IDEs manually on the plugin page.

**Comment by devoncarew** [comment]
> If you want you can disable autodetection and select compatible IDEs manually on the plugin page.

I think that's what we've done - currently (on that page) we just say we're compatible with the CE and Ultimate.

**Comment by alexander-doroshko** [comment]
> I think that's what we've done

May be, I can't see your [plugin settings](https://plugins.jetbrains.com/plugin/edit?pluginId=9212) page :).
That's the 'Determine supported products by dependencies in plugin.xml' check box.

**Comment by devoncarew** [comment]
Yup, looks like we're fully manual.

**Pull request merged**
