### PR TITLE
Don't filter consoles when not in machine mode

### LINKED ISSUE #984: Flutter filter being applied to non-Flutter console
Reported by @tvolkert 

To reproduce:
- create new Flutter app
- create a Dart (not Flutter) script:
```
main() {
  print("[{hello}]");
  print("[{world}");
}
```

- Create a "Dart Command Line App" run configuraiton.

Output is:

```
/usr/local/google/home/skybrian/software/flutter/bin/cache/dart-sdk/bin/dart --checked --enable-vm-service:33759 /usr/local/google/home/skybrian/tmp/click/lib/foo.dart
[{world}
```

It looks like we need to attach `DaemonJsonInputFilterProvider` in code, not in plugin.xml

### PR DESCRIPTION
**Pull request by skybrian**
Fixes #984

### CODE REVIEW

**Comment by skybrian** [comment]
Should I wait to land it? I don't want to mess up the release.

**Comment by pq** [comment]
I was just going to say, hold off for a few while I roll together the release (after I finish testing).

Thanks!

**Comment by skybrian** [comment]
Ok to commit?

**Comment by pq** [comment]
Yep!

**Pull request merged**
