### PR TITLE
Check if bazel is enabled before attempting to load a workspace to fi…

### PR DESCRIPTION
**Pull request by DaveShuckerow**
…x slowness in #4142

### CODE REVIEW

**Comment by devoncarew** [comment]
I'll take a look at the PR; in the meantime, it looks like some related tests are failing:

```
io.flutter.bazel.WorkspaceTest
    ✘ canLoadWorkspaceWithConfigFileAndScriptInReadonly
      java.lang.AssertionError: expected a workspace
          at io.flutter.bazel.WorkspaceTest.canLoadWorkspaceWithConfigFileAndScriptInReadonly(WorkspaceTest.java:84)
    ✘ canLoadWorkspaceWithConfigFile
      java.lang.AssertionError: expected a workspace
          at io.flutter.bazel.WorkspaceTest.canLoadWorkspaceWithConfigFile(WorkspaceTest.java:59)
    ✘ canLoadWorkspaceWithoutConfigFile
      java.lang.AssertionError: expected a workspace
          at io.flutter.bazel.WorkspaceTest.canLoadWorkspaceWithoutConfigFile(WorkspaceTest.java:36)
```

**Comment by jacob314** [comment]
Fix tests to enable bazel.
https://github.com/jacob314/flutter-intellij/pull/new/slowness

**Comment by jacob314** [comment]
https://github.com/flutter/flutter-intellij/pull/4164

**Comment by jacob314** [comment]
Closing as I've landed this with https://github.com/flutter/flutter-intellij/pull/4164

**Pull request closed without merging**
