### PR TITLE
revert some forward looking API changes

### PR DESCRIPTION
**Pull request by devoncarew**
- revert some forward looking API changes
- remove the associated source re-writing
- add todos in the affected places w/ the versions that the newer APIs require
- also, remove support for re-writing source to support Android Studio 3.6

@stevemessick

### CODE REVIEW

**Comment by stevemessick** [comment]
This appears to be the inverse of #4873. I'm unclear why we should do this. We'll have to make the changes eventually, so why not just keep the edits?

**Comment by devoncarew** [comment]
> This appears to be the inverse of #4873. I'm unclear why we should do this.

Yeah, it mostly is. I'm assuming that we'd rather have source code on our disks locally that can work in all our supported versions, instead of relying on a re-write process. We don't have many of these re-writes, so this isn't a huge deal; happy to close this if you'd prefer the current state.

**Comment by stevemessick** [comment]
> I'm assuming that we'd rather have source code on our disks locally that can work in all our supported versions

Now I see. That would be nice, but we haven't had it since Android Studio 3.0. The AS code has incompatible differences with each version. I just keep my local sources sync'd to the latest AS sources, which includes IntelliJ.

I'd prefer to keep what we have.

**Comment by devoncarew** [comment]
Sounds good -

**Pull request closed without merging**
