### PR TITLE
fix flutter log view while resizing

### PR DESCRIPTION
**Pull request by quangson91**
Relate: https://github.com/flutter/flutter-intellij/pull/2361

Fix the filter panel is hidden when the window is narrow.

Reason:
It seems all actions will automatically hide when the window is narrow & auto visible when the mouse hover.

Solution
Keep the filter panel is just a Panel. (we don't wrap it in the action).

Demo:
fix_reisze_flutter_log_view

/cc @pq

### CODE REVIEW

**Comment by pq** [comment]
Nice!  Things changed in the meantime; would you mind rebasing and I can take a fresh look?

**Comment by quangson91** [comment]
@pq yes, I will resolve the conflict.

**Comment by pq** [comment]
Thanks!

**Comment by quangson91** [comment]
I already resolve the conflict.
Please take a look on next week :)
Have a nice weekend!

**Comment by pq** [comment]
Oh no.  I just messed this up again.  

@quangson91: if a rebase isn't too much hassle, would you mind?

Otherwise I can do it.

Sorry! 😦

**Comment by quangson91** [comment]
@pq, I will do it :)

**Comment by pq** [comment]
Thanks!

**Comment by quangson91** [comment]
@pq I resolved the conflict.
PTAL. Thanks!

**Comment by quangson91** [comment]
test this please

**Comment by quangson91** [comment]
retest

**Comment by quangson91** [comment]
How do we re-run travis ci ?

**Comment by pq** [comment]
> How do we re-run travis ci ?

If you click the [build link](https://travis-ci.org/flutter/flutter-intellij/builds/393678636?utm_source=github_status&utm_medium=notification) do you see something like this?

image

**Comment by quangson91** [comment]
I can't see it.
I think I don't have permission.
I though there is some command like "test this please".
So I can comment & the travis auto re-run :D

**Comment by pq** [comment]
That would be cool...  Not aware of that but maybe @devoncarew knows?

In the meantime, I restarted the build. 🤞

**Comment by quangson91** [comment]
Thank you!
I just search on StackOverflow.
There is a trick:
Close PR then Reopen :)

**Comment by quangson91** [comment]
It seemed Travis ci random failed :|

**Comment by quangson91** [comment]
I can only see:
screen shot 2018-06-18 at 11 41 13 pm

**Comment by pq** [comment]
Ah well;  thanks for looking.

Anyway, that break looks unrelated; I restarted again...

**Comment by quangson91** [comment]
Thank you!

**Pull request merged**
