### PR TITLE
Rename copy of debug service and make it a subclass of the real one

### PR DESCRIPTION
**Pull request by stevemessick**
@devoncarew See if this fixes your latest class loader problem with the built plugin.

### CODE REVIEW

**Comment by devoncarew** [comment]
(applying locally now)

**Comment by stevemessick** [comment]
Thanks, cuz if it doesn't work I'd just have to revert this

**Comment by devoncarew** [comment]
OK, this fixes the IllegalAccessExceptions. I do see:

```
Failed to connect to the VM observatory service: java.io.IOException: Failed to connect: ws://null:0/ws
Caused by: de.roderick.weberknecht.WebSocketException: unknown host: null
Caused by: java.net.UnknownHostException: null
/Users/devoncarew/projects/flutter/flutter/bin/flutter daemon

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
Observatory connection never became ready
```

now, but I suspect it's a different issue.

lgtm; I'll file an issue for us to noodle ideas to avoid problems with the dual classloaders going forward

**Comment by stevemessick** [comment]
I get that same "Failed to connect" message the first time I try to start
the debugger after firing up IntelliJ. Then it seems to be fine.

**Comment by devoncarew** [comment]
> I get that same "Failed to connect" message the first time I try to start the debugger after firing up IntelliJ. Then it seems to be fine.

I did confirm, I was able to run and debug after restarting.

**Comment by stevemessick** [comment]
Wait, what? You can do the demo from built plugins and all you say is "it
works"? Shouldn't we be celebrating more? 😂

**Comment by stevemessick** [comment]
I see that emoticons may not convert the proper level of levity. I am
pretty happy right now!

**Comment by devoncarew** [comment]
🎉 🎈 🍰 📈 🎆

**Pull request merged**
