### PR TITLE
Update restart/reload button enablement (#407, #332).

### PR DESCRIPTION
**Pull request by pq**
Updates button enablement to track Flutter app running state.

Addresses some of #407.

Fixes: #332.

/cc @stevemessick @devoncarew

### CODE REVIEW

**Comment by pq** [comment]
Before landing, I'll do some testing against old Flutters to make sure we have a graceful degradation before Dan plumbed in the even notifications.

**Comment by pq** [comment]
Testing against d86900d22f560c627df3551d865f288f89135f6e (right before 1f1adcaa0e563cb68ec5f0d2f82efc9759be1221, which has the relevant changes).

screen shot 2016-11-08 at 2 58 46 pm

No enablement all 👎

**Comment by pq** [comment]
To mitigate, we'll bump the tools version string in the flutter repo and up our check in `SdkConfigurationNotificationProvider`.

**Comment by devoncarew** [comment]
lgtm

**Pull request merged**
