### PR TITLE
re-enable tests on the bots

### PR DESCRIPTION
**Pull request by devoncarew**
- re-enable tests on the bots
- disable two tests that were causing downstream test failures (tracking those disabled tests in https://github.com/flutter/flutter-intellij/issues/3583)

### CODE REVIEW

**Comment by devoncarew** [comment]
hmm:

```
io.flutter.bazel.WorkspaceCacheTest
    ✘ shouldDetectConfigFileChanges
      java.lang.AssertionError: expected a workspace but it doesn't exist
          at io.flutter.bazel.WorkspaceCacheTest.checkNoConfig(WorkspaceCacheTest.java:95)
```

**Comment by devoncarew** [comment]
disable ~two~ three tests

**Comment by devoncarew** [comment]
The bots went green. I'm going to cycle them from the travis UI a few times to see if there are any flakes.

**Comment by devoncarew** [comment]
This flaked after 4 runs:

```
io.flutter.utils.AsyncRateLimiterTest
    ✘ rateLimited
      java.lang.AssertionError: Requests per second does not exceed limit. Actual: 10.101010101010102
          at io.flutter.utils.AsyncRateLimiterTest.rateLimited(AsyncRateLimiterTest.java:106)
```

**Comment by devoncarew** [comment]
added an epsilon to a flaky test

**Comment by devoncarew** [comment]
this one looks flakey as well:

```
io.flutter.bazel.WorkspaceCacheTest
    - shouldDetectConfigFileChanges
    ✘ shouldDetectModuleRootChange
      java.lang.AssertionError: expected a workspace but it doesn't exist
          at io.flutter.bazel.WorkspaceCacheTest.checkWorkspaceExists(WorkspaceCacheTest.java:90)
```

so both WorkspaceCacheTest tests will get disabled...

**Comment by devoncarew** [comment]
re-running to find flakes...

**Comment by devoncarew** [comment]
👍 looks stable

**Comment by stevemessick** [comment]
LGTM

@DaveShuckerow and @jacob314 might want to know about the disabled tests.

**Comment by devoncarew** [comment]
> @DaveShuckerow and @jacob314 might want to know about the disabled tests.

Yup, good point. I updated the top comment in https://github.com/flutter/flutter-intellij/issues/3583 w/ the current list of disabled tests.

**Pull request merged**
