### PR TITLE
Deprecation of BoundField.getDecl() with NPE check (#7228)

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
`getDecl()` was used for 'jump to source' feature (from the Variables view in the Debugger tool window), as well as for icon customization. If the VM still provides this info, maybe keep using it?

**Comment by jwren** [comment]
@alexander-doroshko  Yes, this was my first approach, it was pointed out to me that it is deprecated however, so we shouldn't use it going forward.

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by alexander-doroshko** [comment]
> it is deprecated however, so we shouldn't use it going forward

And looks like there's no replacement, is there? It was a nice feature 😢

**Comment by jacob314** [comment]
Fyi @bkonyi for thoughts on whether there is a replacement or should be.

**Comment by bkonyi** [comment]
The `name` and `value` properties in [`BoundField`](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md#boundfield) should be used instead.

**Pull request merged**
