### PR TITLE
Add IDEA version constraints to plugin.xml (#328).

### PR DESCRIPTION
**Pull request by pq**
Fixes: #328

/cc @alexander-doroshko @devoncarew

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Note that in JetBrains' repos `master` branch currently targets 2017.1, so `since-version` would be `171.1`. For 2016.3 releases there's branch `163` and for 2016.2 - branch `162`. If you decide to follow our branch structure make sure to have appropriate `since-build` and `until-build` in each flutter-plugin branch.

**Comment by pq** [comment]
@alexander-doroshko : what would you recommend we do here?  I'm not familiar with the pros and cons...  We really just want to ensure that a people don't get into a state where they're using the plugin with an incompatible earlier version.

**Comment by alexander-doroshko** [comment]
I recommend that in flutter-plugin repository you have the same branches as in Dart plugin and IntelliJ Community and build compatible plugin build from appropriate branch. In each branch you'll have different Dart.jar that you compile against. And also each branch will have different version of IntelliJ Plugin SDK.

**Comment by alexander-doroshko** [comment]
Pros: you develop and compile against JARs that Flutter-plugin will be executed against in runtime (well, almost)
Cons: everyone will need to understand what these branches are for, and also to have several installations of IntelliJ IDEA (if he/she develops in different branches).

**Comment by pq** [comment]
Good points.

Assuming we *do* want to go this road, are these constraints right for the current 162 Dart plugin?

**Comment by alexander-doroshko** [comment]
One more con: you'll need to carefully make sure that all commits are correctly cherry-picked to each branch where it is expected to be.
So all cons are about discipline and better understanding of the processes.
But the pro is that "code compiles => plugin won't fail", and it is possible with similar branches only.

Still you may have conflicts and incompatibilities when IntelliJ API or Dart plugin API changes within a branch. You may need to have subbranches and/or more granular since/until. The only way to fix ALL incompatibility issue is to run IntelliJ IDEA Community from sources + Dart plugin from sources + Flutter plugin from sources. But with simplified single-module Flutter-plugin project setup the best you can do is to follow our branches structure.

**Comment by alexander-doroshko** [comment]
yes, for 2016.2 these constraints are correct.

**Comment by devoncarew** [comment]
lgtm

We'll need to carefully evaluate our dev process when we decide to support android studio - they use an older version of the IntelliJ APIs.

**Pull request merged**
