### PR TITLE
convert to a new project structure (based on IntelliJ stable)

### PR DESCRIPTION
**Pull request by devoncarew**
- experimenting with a new project structure

Not necessarily for landing; this converts the flutter-intellij repo to a self-contained IntelliJ project and module. It should be able to be opened by a stable copy of IntelliJ CE (`idea .`). A little configuration to provide a `IntelliJ IDEA Community Edition` platform SDK is required. Knock on wood, things should just work?

@pq @stevemessick

### CODE REVIEW

**Comment by devoncarew** [comment]
Looking more promising. Here are the steps:

- download IntelliJ CE stable
- open; set up a platform SDK pointing to CE; name it `IntelliJ IDEA Community Edition` (which is similar to the default name)
- you may already have to have a JDK set up, named `IDEA JDK`; this step we may be able to make optional
- if you have the intellij cli set up, from the git repo root, type `idea .`
- build and run should work!

**Comment by devoncarew** [comment]
@pq, @stevemessick, now for review and feedback :)

Would like to get your thoughts on this PR as a means to develop against IntelliJ stable and Dart plugin stable.

**Comment by stevemessick** [comment]
LGTM

Caveat: I have not tried to use it yet.

Is IntelliJ CE required, or will Ultimate work?

**Comment by pq** [comment]
PS: once landed, maybe you could follow-up with setup docs?

**Comment by devoncarew** [comment]
Either CE or ultimate should work.

Yup - will update the setup docs once this lands.

**Comment by devoncarew** [comment]
(landing - will update docs)

**Pull request merged**
