### PR TITLE
Remove private return type from createState in macros

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter-intellij/issues/5962.
Fixes https://github.com/flutter/flutter-intellij/issues/5964.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
Actually, I would have expected that running `./bin/plugin generate` would have updated the `flutter_miscellaneous.xml` file with these changes as documented in https://github.com/flutter/flutter-intellij/blob/master/resources/liveTemplates/readme.md, but that's not happening. Am I using this wrong?

**Comment by goderbauer** [comment]
Fixed `./bin/plugin generate`, but it is introducing some other changes that I think are not right. I hand-reverted those in https://github.com/flutter/flutter-intellij/pull/5963/commits/023325d398f70e24b64bda86ec792f93b7601127.

**Comment by goderbauer** [comment]
But now the presubmit is failing because what `./bin/plugin generate` generates doesn't match what's in `flutter_miscellaneous.xml`. Previously, this wasn't caught because `./bin/plugin generate` wouldn't actually update `flutter_miscellaneous.xml` due to a bug in the script fixed in this PR. Not sure what to do here, I've filed https://github.com/flutter/flutter-intellij/issues/5964 for this kerfuffle. 😞

**Comment by goderbauer** [comment]
Actually, looks like the templates just can be updated to reflect the manual change from https://github.com/flutter/flutter-intellij/pull/5619. That should make the checks happy again, I hope.

**Comment by goderbauer** [comment]
Yay, that worked. This one is ready for review now.

**Review by stevemessick — APPROVED** [review]
Thanks!

**Pull request merged**
