### PR TITLE
Bump to `0.1.5`.

### PR DESCRIPTION
**Pull request by pq**
/cc @devoncarew

### CODE REVIEW

**Comment by pq** [comment]
Just after pushing this my IDEA caught up with `0.1.4.1`.  Happy to put this on ice until our scheduled release.

**Comment by devoncarew** [comment]
Let's sync tomorrow re a release -

**Comment by pq** [comment]
Yeah.  Given the patch, I think we can defer in the interest of sticking to the schedule but I'm easy!

**Comment by pq** [comment]
Updated `CHANGELOG`.  PTAL.

@devoncarew

**Pull request merged**
