### PR TITLE
🐛 Resolves the referenced element before parsing colors

### LINKED ISSUE #5436: [Enhancement] Display color icon for variables that can be dereferenced to known colors
Currently, the color selector can be parsed and displayed only when the value of the variable explicit starts with "Color" or "Colors", or "CupertinoColors".

Found a related code at https://github.com/flutter/flutter-intellij/blob/28aaecc3078f0f5d065194d64292e920941640d2/src/io/flutter/editor/FlutterColorProvider.java#L41 which abandoned all values other than these patterns.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart' hide Colors;

const Color _c1 = Color(0xff000000);

void test() {
  const Color c1 = _c1;
  const Color c2 = Color(0xffffffff);
  const Color c3 = Color.fromARGB(255, 123, 231, 31);
  const Color c4 = Color(0xff923998);
  const Color c5 = c2;
  const Color c6 = TC.c1;
  const Color c7 = TC.c2;
  const Color c8 = Colors.black;
}

class TC {
  static const Color c1 = Color(0xff449978);
  static const Color c2 = Color(0xffdb2f7f);
}

class Colors {
  static const Color black = Color(0xffcccccc);
}
```

image

## Version info

Flutter 2.0.5.

### PR DESCRIPTION
**Pull request by AlexV525**
Fixes #5436 #6777.

The PR does:
- Resolves PSI elements if they are `VAR_INIT` or `FUNCTION_BODY` before parsing, which can always lead to a correct definition eventually.
- Improve `const Color.from*` constructors handling.
- Only handle the last child of an element's children to avoid too many requests when gathering line markers, thus `Colors.blue.shade700` will only resolve color on `shade700` instead of `Colors`, `blue`, and `shade700`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
What's the status of this PR?

**Comment by AlexV525** [comment]
> What's the status of this PR?

The PR itself fixes the issue, however it might has some compatibility issue with the older IntelliJ platform. Still trying to investigate.

**Comment by AlexV525** [comment]
@stevemessick We've dropped 2022.1 support already, and the exception about `substring` has been resolved by 37f0e3f. I think we might be good to go this time.

**Comment by stevemessick** [comment]
@AlexV525 I'm no longer on the Dart team. You should check with @jacob314 @jwren and @helin24 for future reviews.

I noticed a couple unit tests that failed. You might want to see if the tests in `FlutterColorProviderTest` need to be updated.

**Comment by AlexV525** [comment]
> @AlexV525 I'm no longer on the Dart team. You should check with @jacob314 @jwren and @helin24 for future reviews.

Sorry to hear that. Hope you'll be well in the next trip!

> I noticed a couple unit tests that failed. You might want to see if the tests in `FlutterColorProviderTest` need to be updated.

I'll check them later, thanks.

**Review by helin24 — APPROVED** [review]
Thanks for your contribution (and your patience)!

**Pull request merged**
