### PR TITLE
changed the depreciated JxBrowser link in flutter JetBrains plugin documentation

### PR DESCRIPTION
**Pull request by SulaimanHasan411**
Updated the link in plugin.xml (and plugin_template.xml) to the updated link from issue #7271. This allows users to access the current source code and removes the depreciated link.  

Addresses issue #7271 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by helin24 — APPROVED** [review]

**Comment by jwren** [comment]
Thanks for the change.  I think that the change needs some change in text "Use the instructions and build script" doesn't make sense with the new URL, or am I missing something?  @helin24

**Comment by helin24** [comment]
We used to link to the relinking file, which is featured in the new link, so I feel like it's okay. I guess to be more accurate, we could say "The LGPL requirements are at <link>; here you can also download the build script to relink with modified components."

**Comment by SulaimanHasan411** [comment]
I have updated the text based on your comment. If it is possible can the original commit be removed so that this is able to work? 
Thank you.

**Review by jwren — APPROVED** [review]

**Comment by helin24** [comment]
Closing this for signed commits.

**Pull request closed without merging**
