### PR TITLE
19.1

### PR DESCRIPTION
**Pull request by pq**
19.1:

<ul>
  <li>Bazel run configuration updates</li>
</ul>

@devoncarew @jwren

### CODE REVIEW

**Comment by jwren** [comment]
LGTM

**Comment by devoncarew** [comment]
```
pq  wants to merge 2 commits into master from release_19.0
```

I think this is up-to-date: https://github.com/flutter/flutter-intellij/wiki/Releasing#pushing-a-patch-to-an-existing-release

(generally you'll want to git cherry-pick a commit from master into the existing release branch)

**Comment by pq** [comment]
Right.  I did that actually.  This was just me merging the plugin.xml changes back into master.  It looks like Jaime's commit showed up too but it was a no-op.  I agree though it looks odd even if it got us to the same place.  Sorry for the confusion!

Next time I'll create a second commit on master to back-port the plugin.xml changes. 👍

**Comment by devoncarew** [comment]
> This was just me merging the plugin.xml changes back into master.

Ah, cool, thanks for the clarification :)

**Pull request merged**
