### PR TITLE
Suggest user to run 'flutter doctor' if Flutter SDK installation is not complete (#415)

### PR DESCRIPTION
**Pull request by alexander-doroshko**
Address #415.
@pq @devoncarew 
Ideas about better wording are welcome.
image

### CODE REVIEW

**Comment by lukechurch** [comment]
Is there some way we can launch it from within IJ?

If not, then I'd suggest at least advising that they do this from the terminal. Is there a predictable way of know where they should run it, in case the installation hasn't set the paths?

**Comment by alexander-doroshko** [comment]
> Is there some way we can launch it from within IJ?

Technically possible, but a lot of work and not sure about the best UI for 'flutter doctor' output. One more modal dialog with Terminal-like functionality..? I think we are good with an error message at this point.

> If not, then I'd suggest at least advising that they do this from the terminal. Is there a predictable way of know where they should run it, in case the installation hasn't set the paths?

If paths are not set then [Flutter SDK]/bin/flutter is the correct script to run. Suggestions on better text are welcome (the shorter the better :)).

**Comment by pq** [comment]
> Technically possible, but a lot of work and not sure about the best UI for 'flutter doctor' output.

As it happens we do support running `flutter doctor` (from a console hyperlink in `flutter create` output) but it's only minimal.  It prints it's output to the console and is not actionable beyond that.  In the medium run we'll want to add better support.


Alternatively, we could link out to external docs on installing flutter?

Something like:

> Error: This Flutter SDK installation is incomplete; setup instructions [here](https://flutter.io/setup/#get-the-flutter-sdk).

but word-smithed? -- paging @mit-mit !

**Comment by alexander-doroshko** [comment]
How about this? Should some part of the error text be red as it was before?
image

**Comment by eseidelGoogle** [comment]
I may be missing something obvious, but how would one run `flutter doctor`
if one doesn't know where the flutter sdk is (which contains `flutter
doctor`)?

**Comment by pq** [comment]
Better integration of `flutter doctor` is high on my list of things to address down the road.  TBH I'm not sure what it will look like but we've clearly got a ways to go.

In the meantime,

> I may be missing something obvious, but how would one run `flutter doctor`
if one doesn't know where the flutter sdk is (which contains `flutter
doctor`)?

I'm hoping the setup instructions hyperlinked in the message will be sufficient to get folks moving.  This is the link:

https://flutter.io/setup/#get-the-flutter-sdk

Maybe there's a better one?

Or if you have ideas for a better message or action, please do chime in!

**Comment by alexander-doroshko** [comment]
>  how would one run `flutter doctor` if one doesn't know where the flutter sdk is

Hyperlink or advice to run 'flutter doctor' is shown if flutter sdk path is correct but it doesn't contain dart sdk inside. If selected path is not a flutter sdk at all we still show as before: 'Error: Flutter SDK is not found in the specified location.'

**Comment by pq** [comment]
LGTM!

**Comment by alexander-doroshko** [comment]
I haven't added a code with the link yet, only a screenshot. :)
So, is black error text ok (was red)?
For errors without link - black text too?
Text - ok?
```
Error: path to the Flutter SDK is not specified.
Error: the folder specified as the Flutter SDK home does not exist.
Error: Flutter SDK is not found in the specified location.
Error: Flutter SDK installation is incomplete, see <a href='https://flutter.io/setup/#get-the-flutter-sdk'>setup instructions</a>.
```

**Comment by pq** [comment]
> So, is black error text ok (was red)?
> For errors without link - black text too?
> Text - ok?

I'm neutral about black vs. red text.  Whatever is most consistent with how errors are presented elsewhere in IntelliJ?  If that's not easy to answer, I say pick one and we can always revisit.

Thanks!

**Pull request merged**
