### PR TITLE
Add reload reason analytics

### PR DESCRIPTION
**Pull request by pq**
Fixes: #2682.

/cc @DanTup @devoncarew

### CODE REVIEW

**Comment by DanTup** [comment]
@pq Sorry, I didn't see this till this morning. It all looks good to me too - though I didn't understand what the code in `RenderHelper` was for (and why it would be recorded as `save`).

**Comment by pq** [comment]
No worries.  Thanks @DanTup !  The `RenderHelper` bit is part of the preview pane.  I opted not to distinguish it from an auto-save since I think the really interesting # is manual vs. non-manual.  If folks are interested in more precise analytics, I'm happy to make the distinction.

/cc @scheglov

**Comment by pq** [comment]
Cool.  Alternatively, we could add a third category (like `tool` or something) that is used for things like the render helper if we want to keep that analytic distinct.  That has the benefit of leaving the existing data streams alone.

/cc @devoncarew

**Comment by devoncarew** [comment]
Definitely agree that we shouldn't record is as a manual save. Since it's just plumbing for an automatic feature, perhaps we could decide not to record that event at all?

**Comment by DanTup** [comment]
Do you mean not to record the reason? Not recording the event is tricky since it's recorded in flutter tools (it's the reload event). I think if we want to separate it from normal save-triggered-reloads, setting it to `tool` as @pq suggests may make most sense?

**Comment by devoncarew** [comment]
Ah, gotcha. Then a separate category makes sense (`tool`), and flutter_tools could then choose to record it as that, or ignore it completely.

**Comment by DanTup** [comment]
The tools just pass through the string directly to analytics in a custom dimension so I think it makes sense to just let it go through. If someone wants to filter them out, they can it at reporting time, so the raw data isn't lost.

**Pull request merged**
