### PR TITLE
Prepare for point release 76.2.X, Android Studio Iguana, 2023.2 and IntelliJ EAP, 2023.3

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by devshubhdroid** [comment]
@jwren Are we waiting for some other tasks to be completed before we merge this?

**Comment by jwren** [comment]
Yes, and have been a work in progress for a bit for me.  The errors in the presubmit here are accurate.

I have been navigating a way forward here, either by getting the APIs migrated forward, or the AndroidStudio support removed (which I'm trying to avoid.)

My hope is for the next major version of the Flutter Plugin for IntelliJ (77.0) to have Iguana supported (~first half of December).

**Comment by devshubhdroid** [comment]
Good to hear this 🎉 Thanks a lot for all your efforts 👏🏼

**Comment by devshubhdroid** [comment]
> Yes, and have been a work in progress for a bit for me. The errors in the presubmit here are accurate.
> 
> I have been navigating a way forward here, either by getting the APIs migrated forward, or the AndroidStudio support removed (which I'm trying to avoid.)
> 
> My hope is for the next major version of the Flutter Plugin for IntelliJ (77.0) to have Iguana supported (~first half of December).


Good to hear this 🎉 Thanks a lot for all your efforts 👏🏼

**Comment by jwren** [comment]
Closing this PR, replaced with https://github.com/flutter/flutter-intellij/pull/7112

**Pull request closed without merging**
