### PR TITLE
[WIP] Binary artifacts, but cannot be merged

### LINKED ISSUE #6072: Project is out of compliance with Binary Artifacts policy: binaries present in source code
**Security Policy Violation**
Project is out of compliance with Binary Artifacts policy: binaries present in source code

**Rule Description**
Binary Artifacts are an increased security risk in your repository. Binary artifacts cannot be reviewed, allowing the introduction of possibly obsolete or maliciously subverted executables. For more information see the [Security Scorecards Documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#binary-artifacts) for Binary Artifacts.

**Remediation Steps**
To remediate, remove the generated executable artifacts from the repository.

**Artifacts Found**

- flutter-gui-tests/gradle/wrapper/gradle-wrapper.jar
- gradle/wrapper/gradle-wrapper.jar
- lib/dart-plugin/212.5486/Dart.jar
- lib/dart-plugin/212.5486/resources_en.jar
- lib/dart-plugin/deps/json.jar
- lib/dart-plugin/deps/weberknecht-0.1.5.jar
- lib/java-string-similarity-2.0.0.jar
- lib/jxbrowser/jxbrowser-7.22.jar
- lib/jxbrowser/jxbrowser-swing-7.22.jar

**Additional Information**
This policy is drawn from [Security Scorecards](https://github.com/ossf/scorecard/), which is a tool that scores a project's adherence to security best practices. You may wish to run a Scorecards scan directly on this repository for more details.

### PR DESCRIPTION
**Pull request by stevemessick**
Fixes #6072

### CODE REVIEW

**Comment by Hixie** [comment]
These files are in violation of Google's third-party policies.

All third-party files must be in a third_party subdirectory with clear license terms.

**Comment by Hixie** [comment]
(Separate from that, you'll need to have us update the central configuration — our allstar configuration disables per-repo configs so that we can audit it all easily, so this PR won't actually work.)

**Comment by stevemessick** [comment]
Thanks for the clarification!

**Comment by godofredoc** [comment]
Thanks, @Hixie. I'll ask if we can opt out individual files.

**Comment by stevemessick** [comment]
We should include a script to run the Gradle wrapper when it moves into third_party. The alternative would be symlinks, which just cause problems on Windows, so let's not do that. We will need scripts for both Mac/Linux and Windows.

@Hixie do we have a deadline for compliance?

**Comment by godofredoc** [comment]
> We should include a script to run the Gradle wrapper when it moves into third_party. The alternative would be symlinks, which just cause problems on Windows, so let's not do that. We will need scripts for both Mac/Linux and Windows.
> 
> @Hixie do we have a deadline for compliance?

There is no deadline yet, but given that having binaries checked in is consider a high risk I'd recommend that we aim for <2 weeks.

For the next step I'll opt out flutter-intellij temporarily while we work towards the final solution.

@blasten are there any java third party dependency management best practices that can help us here?

**Comment by stevemessick** [comment]
Thanks @godofredoc! We shouldn't need two weeks. #6087 will take care of it.

**Comment by stevemessick** [comment]
Close this, since it can't be merged and another PR (#6087) is out for review.

**Pull request closed without merging**
