### PR TITLE
address an issue with the JxBrowser singleton

### PR DESCRIPTION
**Pull request by devoncarew**
- address an issue with the JxBrowser singleton (we were creating it but not remembering it)
- some minor additions wrt nullability annotations

cc @helin24

### CODE REVIEW

**Review by helin24 — APPROVED** [review]
Thanks!

**Comment by devoncarew** [comment]
Thanks for the review!

@stevemessick - the kokoro bot has failed twice on this PR (on the original PR, and then on a whitespace change). It's not immediately obvious to me why from looking at the log - any ideas?

**Comment by stevemessick** [comment]
It looks like ant changed its current version. I'm not sure we even need ant anymore on Kokoro. Ant is only used to compile with Java 8, and I think Kokoro only uses Java 11.

**Comment by devoncarew** [comment]
Thanks Steve! This is passing now.

**Pull request merged**
