### PR TITLE
Print api report

### PR DESCRIPTION
**Pull request by devoncarew**
- print an API report for uses of the Dart plugin API
- remove some unused imports
- print the api report as part of travis
- fix https://github.com/flutter/flutter-intellij/issues/190

### CODE REVIEW

**Comment by devoncarew** [comment]
(looks like the gradle-intellij-plugin we're using rev'd over the weekend - this is breaking our build)

**Comment by devoncarew** [comment]
Oddly enough, builds work for me locally, even when I blitz my gradle cache and re-download everything.

**Comment by devoncarew** [comment]
@pq @stevemessick (hoping for a green build)

**Comment by devoncarew** [comment]
Current report:

### 28 separate Dart plugin APIs used
  
```
        arguments: ['grep', 'import com.jetbrains.lang.dart.'],:
    tool/grind.dart
  
  com.jetbrains.lang.dart.DartFileType:
    src/io/flutter/inspections/WrongDartSdkConfigurationNotificationProvider.java
    src/io/flutter/run/FlutterRunConfigurationType.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.DartLanguage:
    src/io/flutter/inspections/WrongDartSdkConfigurationNotificationProvider.java
  
  com.jetbrains.lang.dart.analyzer.DartAnalysisServerService:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.ide.DartWritingAccessProvider:
    src/io/flutter/run/FlutterRunConfigurationProducer.java
  
  com.jetbrains.lang.dart.ide.runner.DartRunner:
    src/io/flutter/run/FlutterRunner.java
  
  com.jetbrains.lang.dart.ide.runner.ObservatoryConnector:
    src/io/flutter/actions/FlutterAppAction.java
    src/io/flutter/actions/FlutterKeyAction.java
    src/io/flutter/actions/HotReloadFlutterApp.java
    src/io/flutter/actions/HotReloadFlutterAppKeyAction.java
    src/io/flutter/actions/RestartFlutterApp.java
    src/io/flutter/actions/RestartFlutterAppKeyAction.java
    src/io/flutter/run/FlutterRunner.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.ide.runner.base.DartDebuggerEditorsProvider:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.ide.runner.base.DartRunConfigurationBase:
    src/io/flutter/run/FlutterRunConfiguration.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
  
  com.jetbrains.lang.dart.ide.runner.server.DartCommandLineRunConfiguration:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
  
  com.jetbrains.lang.dart.ide.runner.server.DartCommandLineRunnerParameters:
    src/io/flutter/run/FlutterRunConfigurationProducer.java
    src/io/flutter/run/FlutterRunnerParameters.java
  
  com.jetbrains.lang.dart.ide.runner.server.DartCommandLineRunningState:
    src/io/flutter/run/FlutterAppState.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
  
  com.jetbrains.lang.dart.ide.runner.server.DartRemoteDebugConfiguration:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
  
  com.jetbrains.lang.dart.ide.runner.server.OpenDartObservatoryUrlAction:
    src/io/flutter/actions/OpenComputedUrlAction.java
    src/io/flutter/run/FlutterAppState.java
  
  com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcessZ:
    src/io/flutter/actions/FlutterKeyAction.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
  
  com.jetbrains.lang.dart.ide.runner.server.vmService.frame.DartVmServiceStackFrame:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.ide.runner.test.DartTestRunnerParameters:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
  
  com.jetbrains.lang.dart.psi.DartFile:
    src/io/flutter/run/FlutterRunConfigurationProducer.java
  
  com.jetbrains.lang.dart.psi.DartImportStatement:
    src/io/flutter/run/FlutterRunConfigurationProducer.java
  
  com.jetbrains.lang.dart.sdk.DartConfigurable:
    src/io/flutter/sdk/FlutterIdeaSdkService.java
  
  com.jetbrains.lang.dart.sdk.DartSdk:
    src/io/flutter/inspections/WrongDartSdkConfigurationNotificationProvider.java
    src/io/flutter/run/daemon/FlutterDaemonController.java
    src/io/flutter/sdk/FlutterSdkUtil.java
    testSrc/io/flutter/sdk/FlutterSdkUtilTest.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
    third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
  
  com.jetbrains.lang.dart.sdk.DartSdkGlobalLibUtil:
    src/io/flutter/sdk/FlutterSdkUtil.java
    third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
  
  com.jetbrains.lang.dart.sdk.DartSdkUpdateOption:
    src/io/flutter/sdk/FlutterSdkUtil.java
  
  com.jetbrains.lang.dart.sdk.DartSdkUtil:
    third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
  
  com.jetbrains.lang.dart.util.DartResolveUtil:
    src/io/flutter/run/FlutterRunConfigurationProducer.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.util.DartTestUtils:
    testSrc/io/flutter/FlutterCodeInsightFixtureTestCase.java
  
  com.jetbrains.lang.dart.util.DartUrlResolver:
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
    third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
  
  com.jetbrains.lang.dart.util.DartUrlResolverImpl:
    src/io/flutter/run/FlutterRunner.java
```

**Comment by pq** [comment]
Oh!  This looks awesome.  Hilariously, dependency management is also on my mind! (see: https://github.com/flutter/flutter-intellij/pull/223).

**Comment by pq** [comment]
Needless to say, LGTM!

**Pull request merged**
