### PR TITLE
redux of some of our icons, actions, and where they're contributed

### PR DESCRIPTION
**Pull request by devoncarew**
- redux of some of our icons, actions, and where they're contributed
- use different icons for 'open observatory' and 'open the timeline view'

This does some rationalization of our icons and actions. This will have merge conflicts with https://github.com/flutter/flutter-intellij/pull/1400, so I'll wait to merge until that's in.

@pq @stevemessick

### CODE REVIEW

**Comment by devoncarew** [comment]
Yup, good point. They're a bit out of date currently anyway - this will be a good reason to circle back an update them.

Definitely the screen shot here: https://flutter.io/intellij-ide/ (under advanced debugging) is out of date now.

**Comment by LarkAscending** [comment]
@devoncarew is the added refresh icon used somewhere??

**Comment by devoncarew** [comment]
It is not :) I wasn't 100% happy with the icon I came up with - the source assets didn't have enough resolution to scale down well. I'm still using the default IntelliJ action for a full restart, but did commit this one with the PR so I didn't have to redo work if we decided to move over to it.

**Comment by devoncarew** [comment]
And for posterity, here are what the new icons and actions look like:

screen shot 2017-10-19 at 2 32 27 pm

screen shot 2017-10-19 at 2 32 38 pm

screen shot 2017-10-19 at 2 32 49 pm

**Comment by devoncarew** [comment]
oops, @jacob314, I did not mean to land this before your PR - I'll see about a PR into your PR to make merging easier

**Pull request merged**
