### PR TITLE
rename the remove widget action

### PR DESCRIPTION
**Pull request by devoncarew**
- rename the "Replace widget with its children" to "remove widget action"
- fix https://github.com/flutter/flutter-intellij/issues/3898
- remove the feedback button from the Flutter Outline view - this was added to get initial feedback on the view
- move an action (the show only widgets filter) to the 'title actions' toolbar for the view; this gives more horizontal space for the build method manipulation actions

### CODE REVIEW

**Comment by InMatrix** [comment]
@DanTup The action's name in VS Code probably needs to be updated, too.

**Comment by DanTup** [comment]
In almost all places in VS Code, this text comes straight from the server. We did have "Remove widget" on the context menu for the Flutter Outline though, so I've changed that to "Remove this widget" to match.

@devoncarew is this being done in the server too?

**Comment by devoncarew** [comment]
@scheglov - does this action have a text name in the server, or just the ID (`dart.assist.flutter.removeWidget`)?

**Comment by scheglov** [comment]
It has both id and text.
https://github.com/dart-lang/sdk/blob/ad7374fcdb9f2af9fd75edde86efc5c2893d4975/pkg/analysis_server/lib/src/services/correction/assist.dart#L136

**Comment by devoncarew** [comment]
https://dart-review.googlesource.com/c/sdk/+/119480

**Pull request merged**
