### PR TITLE
Highlight Outline tree background for Flutter elements.

### PR DESCRIPTION
**Pull request by scheglov**
This PR is mostly to demo that we can change background.
I'm not sure that we want to, or that the color is right :-)
image

### CODE REVIEW

**Comment by devoncarew** [comment]
Cool! I think we also have the ability to prefix more than one icon to a node, so we could have an icon that meant 'flutter widget', in addition to show a icon per widget type.

**Comment by devoncarew** [comment]
This one for instance: https://github.com/flutter/flutter-intellij/blob/master/resources/icons/flutter%402x.png.

**Comment by devoncarew** [comment]
I think we've gone a long way here w/ the flutter badge icons.

If we do want to land something like there, there are some theme colors we could use. The Project view has a different background color for items that are excluded from the project (separate from the selected item background color):

screen shot 2018-02-23 at 2 37 46 pm

And the tree view there also shows items that git thinks are modified with a different text foreground color.

I think using the background color might be a it more than we need, but we could experiment w/ it - land it and back it out if we think it's too busy.

**Comment by scheglov** [comment]
Closing for now.

**Pull request closed without merging**
