### PR TITLE
Edit loadClasses method for 2021.2 as well

### LINKED ISSUE #5683: JxBrowser installation failed with IDEA 2021.2
After upgraded to from 2021.1 to 2021.2, I got the installation failed with JxBrowser which makes me unable to use the embedding inspector.

I tried to re-download these libs, reinstall the plugin and the IDEA, but I got no luck.

```log
2021-07-30 09:41:37,090 [ 500908]   INFO - ter.jxbrowser.JxBrowserManager - flutter_wechat_assets_picker: Retrying JxBrowser installation 
2021-07-30 09:41:37,091 [ 500909]   INFO - ter.jxbrowser.JxBrowserManager - flutter_wechat_assets_picker: Installing JxBrowser 
2021-07-30 09:41:56,080 [ 519898]   INFO - ter.jxbrowser.JxBrowserManager - flutter_wechat_assets_picker: JxBrowser file downloaded: /Users/alex/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/flutter-intellij/jxbrowser/jxbrowser-mac-7.16.jar 
2021-07-30 09:42:07,997 [ 531815]   INFO - ter.jxbrowser.JxBrowserManager - flutter_wechat_assets_picker: JxBrowser file downloaded: /Users/alex/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/flutter-intellij/jxbrowser/jxbrowser-7.16.jar 
2021-07-30 09:42:08,719 [ 532537]   INFO - ter.jxbrowser.JxBrowserManager - flutter_wechat_assets_picker: JxBrowser file downloaded: /Users/alex/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/flutter-intellij/jxbrowser/jxbrowser-swing-7.16.jar 
2021-07-30 09:42:08,720 [ 532538]   INFO - ter.jxbrowser.JxBrowserManager - Loaded JxBrowser file successfully: /Users/alex/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/flutter-intellij/jxbrowser/jxbrowser-mac-7.16.jar 
2021-07-30 09:42:08,720 [ 532538]   INFO - ter.jxbrowser.JxBrowserManager - Loaded JxBrowser file successfully: /Users/alex/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/flutter-intellij/jxbrowser/jxbrowser-7.16.jar 
2021-07-30 09:42:08,720 [ 532538]   INFO - ter.jxbrowser.JxBrowserManager - Loaded JxBrowser file successfully: /Users/alex/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/flutter-intellij/jxbrowser/jxbrowser-swing-7.16.jar 
2021-07-30 09:42:08,720 [ 532538]   INFO - ter.jxbrowser.JxBrowserManager - Failed to find JxBrowser class 
```

### PR DESCRIPTION
**Pull request by helin24**
Fixes #5683

### CODE REVIEW

**Review by stevemessick — APPROVED** [review]

**Comment by AlexV525** [comment]
It's a little bit of shocking that these are hard-coded fixes. 😮

**Comment by helin24** [comment]
@AlexV525 ha sorry. I wonder if we could add a way to specify a min version of IntelliJ to apply edits?

**Comment by AlexV525** [comment]
> @AlexV525 ha sorry. I wonder if we could add a way to specify a min version of IntelliJ to apply edits?

That would good enough AFAIK, and users might don't have to wait for a new version of the plugin.

**Comment by cdprete** [comment]
Hi.
Probably you need to apply this also to version 2021.3 now since I'm experiencing the original issue on such version now.

**Pull request merged**
