### PR TITLE
de-dupe device names

### PR DESCRIPTION
**Pull request by devoncarew**
- ensure that we show a unique name in the device dropdown - if there are different devices with the same name, display the name with the device id as well (some work towards https://github.com/flutter/flutter-intellij/issues/1244)

So, Instead of `Foo Device`, show `Foo Device (device-id)`.

### CODE REVIEW

**Comment by devoncarew** [comment]
This PR just shows the short device name in the combo box, and the full name in the pulldown list. It is a bit of a disconnect, but the longer name seemed to take up too much name in the toolbar....

**Comment by devoncarew** [comment]
@stevemessick @pq

**Comment by eturk1** [comment]
16.0 plugin got pushed out to my machine last night. Now there's a bunch of "emulators" listed... but I only have one AVD built.
image


adb devices (while Nexus 5 emulator is running) >
List of devices attached
emulator-5554   device
emulator-5568   host
emulator-5566   host
emulator-5564   host

**Comment by devoncarew** [comment]
I don't think this is related to the update. It's listing one AVD (at the end of the menu), and 4 running android devices.

`adb devices -l` _may_ give you a bit more information. Restarting the emulator might clear out the others? This sounds like an adb specific issue, and perhaps something that a google search may turn up info for.

**Pull request merged**
