### PR TITLE
Remove the isFailure option in the Dart test event framework

### PR DESCRIPTION
**Pull request by jwren**
https://github.com/dart-lang/test/issues/1465

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]
👍 thanks!

**Comment by jwren** [comment]
I am still doing some research on the IJ test APIs, but am landing this as an incremental step.

**Comment by devoncarew** [comment]
@jwren - I think this is now slightly out of sync w/ what was landed in https://github.com/JetBrains/intellij-plugins/commit/9bf7b23b8c8aa8e1ec19ec98c6248d413a84d629

**Comment by jwren** [comment]
@devoncarew yes it is, I have a follow up PR here: https://github.com/flutter/flutter-intellij/pull/5369

**Pull request merged**
