### PR TITLE
switch to using the org.java-websocket:Java-WebSocket library

### PR DESCRIPTION
**Pull request by devoncarew**
- switch to using the org.java-websocket:Java-WebSocket library

This brings the TooTallNate `Java-WebSocket` library in via maven. This is an alternative to https://github.com/flutter/flutter-intellij/pull/3993; we'll likely want to update the Dart plugin as well.

### CODE REVIEW

**Comment by devoncarew** [comment]
Hmm, some build problems here:
- https://travis-ci.org/flutter/flutter-intellij/jobs/602434675#L681
- https://travis-ci.org/flutter/flutter-intellij/jobs/602434668#L653

**Comment by stevemessick** [comment]
I think it is already approved. LGTM

**Comment by devoncarew** [comment]
@alexander-doroshko, I'm thinking about converting the service protocol library over to use a different websocket library impl. Do you have any thoughts or concerns here? We're using maven to bring the library in for the flutter plugin, but I imagine for the dart plugin we'd just use the straight jar file.

**Comment by alexander-doroshko** [comment]
@devoncarew I'm fine with that. In the Dart plugin it should be a module level maven-based library (just like `"org.apache.commons:commons-lang3:3.9"` in `intellij.dart.iml` and `Dart-community.iml`).

**Comment by devoncarew** [comment]
tabling for now

**Pull request closed without merging**
