### PR TITLE
add a lint command to the plugin tool

### PR DESCRIPTION
**Pull request by devoncarew**
- add a new `lint` command to the plugin tool (open to ideas for the name of the command :) )
- move the code to print our dart plugin api usage from tool/grind.dart to the `plugin lint` command
- also, add checks for imports of annotations that we want to avoid
- add a plugin.sh script to the root of the repo, and
- run the lint as part of our travis jobs (`./plugin.sh lint`)

@stevemessick

### CODE REVIEW

**Comment by stevemessick** [comment]
Also, I was going to put the script in a bin directory so I didn't have the project root on my $PATH.

**Comment by devoncarew** [comment]
- oops, added `plugin.sh` to the PR, and renamed to just `plugin`
- updated the travis script to point to that

re: where the script lives, were you thinking of something like `bin/plugin`? Happy to move there, or we could do in a follow up PR.

**Comment by devoncarew** [comment]
Travis seems unhappy: https://travis-ci.org/flutter/flutter-intellij/jobs/299999179#L541 - will investigate in the morning.

**Comment by stevemessick** [comment]
Yes, I was thinking of bin/plugin for the script.

**Comment by devoncarew** [comment]
Current output of the tool:

```
A script to build, test, and deploy the Flutter IntelliJ plugin.

Usage: plugin <command> [arguments]

Global options:
-h, --help            Print this usage information.
-r, --release=<id>    The release identifier; the numeric suffix of the git branch name

Available commands:
  build    Build a deployable version of the Flutter plugin, compiled against the specified artifacts.
  deploy   Upload the Flutter plugin to the JetBrains site.
  gen      Generate a valid plugin.xml for the Flutter plugin from the template.
  help     Display help information for plugin.
  lint     Perform simple validations on the flutter-intellij repo code.
  test     Run the tests for the Flutter plugin.

Run "plugin help <command>" for more information about a command.
```

**Comment by devoncarew** [comment]
kk, moved the script to `bin/plugin` in this PR; will wait for travis to go green before landing

**Pull request merged**
