### PR TITLE
Shorten labels to improve readability

### PR DESCRIPTION
**Pull request by stevemessick**
@devoncarew @pq

Reduce the complexity of the labels on the check boxes to make them easier to read.

### CODE REVIEW

**Comment by pq** [comment]
Works for me but will defer to @mit-mit or @devoncarew who may have stronger thoughts.

**Comment by mit-mit** [comment]
I would phrase this as 'Include Kotlin support for Android code'

**Comment by stevemessick** [comment]
Done. PTAL

**Comment by stevemessick** [comment]
Oops! Thanks for catching that. Updated.

**Pull request merged**
