### PR TITLE
Context menu for `flutter.yaml` files (#516)

### PR DESCRIPTION
**Pull request by pq**
Fixes: #516.

screen shot 2016-12-12 at 3 37 45 pm

/cc @devoncarew

### CODE REVIEW

**Comment by mit-mit** [comment]
Why a context menu as opposed to adding two more actions next to upgrade and doctor?

**Comment by pq** [comment]
> Why a context menu as opposed to adding two more actions next to upgrade and doctor?

My thinking is that the toolbar would be too crowded and that these actions are the less frequently needed (making them good candidates for a context menu).  I'm open to discussion though.

**Comment by mit-mit** [comment]
I think they should just as common, if not more common? At least once things stabilize a bit, I would expected packages to rev much more frequently than the core framework.

**Comment by pq** [comment]
Updated butterbar:

screen shot 2016-12-13 at 10 30 35 am

Label-smithing welcome.

@devoncarew @mit-mit

**Comment by mit-mit** [comment]
Looks great, labels good as they are!

**Comment by devoncarew** [comment]
Can you update to only have a JSeparator between the "project" related actions and the "global" related ones? Flutter upgrade acts on both, so it's an odd duck, but I'd put the splitter after it.

**Comment by pq** [comment]
> Can you update to only have a JSeparator between the "project" related actions and the "global" related ones? Flutter upgrade acts on both, so it's an odd duck, but I'd put the splitter after it.

👍

**Comment by devoncarew** [comment]
👍 lgtm

**Pull request merged**
