### PR TITLE
have the reloading... notification timeout after the reload completes

### PR DESCRIPTION
**Pull request by devoncarew**
- have the 'reloading...' notification timeout after the reload completes (work around an issue with the IntelliJ Notification.expire() implementation - this does not remove notifications displayed for tool windows)

This addresses an issue there the `Reloading...` tool window notification will continue to show after the reload is complete (until the next time the user interacts with the IDE).

### CODE REVIEW

**Comment by efortuna** [comment]
Thanks, Jaime!!

**Comment by jwren** [comment]
This was Devon's PR, I just reviewed.  :)

**Comment by efortuna** [comment]
oh, :-P Thanks Devon!!!

**Pull request merged**
