### PR TITLE
WIP update setting pref for flutter log

### PR DESCRIPTION
**Pull request by quangson91**
Update setting pref for flutter log including:
+ show column level/timestamp/category/seq, show color 
+ checkbox regex/match case/ log level.

### CODE REVIEW

**Comment by quangson91** [comment]
Wait for other PRs:
https://github.com/flutter/flutter-intellij/pull/2411
https://github.com/flutter/flutter-intellij/pull/2412

**Comment by pq** [comment]
@quangson91: would you mind pulling out just the preference setting and persisting bits into a separate PR?  I'd love to land that and continue some of the other discussions independently.

Thanks in advance!

**Comment by pq** [comment]
Specifically, I mean removing the dependency on #2411.

**Comment by quangson91** [comment]
@pq, I got it.
But if we don't refactor the code first, the method create log columns will so long.

#2411 is only about extract logic create columns for separate methods.

**Comment by pq** [comment]
> #2411 is only about extract logic create columns for separate methods.

I think if we're going to do that (and I don't object), I'd prefer extracting Render classes.  I'll go ahead and do that; PR to follow. 👍

**Comment by quangson91** [comment]
@pq, I'm closing this PR.
After PR https://github.com/flutter/flutter-intellij/pull/2413 merged
=> I will make another PR for `update setting pref for flutter log`

**Comment by pq** [comment]
Super.  Thanks for your flexibility!

**Pull request closed without merging**
