### PR TITLE
Remove checked mode Flutter Run option (#403).

### PR DESCRIPTION
**Pull request by pq**
See: #403 

/cc @alexander-doroshko @devoncarew

### CODE REVIEW

**Comment by pq** [comment]
Or @stevemessick 👍

**Comment by alexander-doroshko** [comment]
I wanted to say that you should remove it from `FlutterRunnerParameters` as well, but it appears that `FlutterRunnerParameters` is an empty subclass of `DartCommandLineRunnerParameters`. Not sure that you anywhere need `FlutterRunnerParameters` to be `DartCommandLineRunnerParameters`. Since the set of parameters is going to be completely different you may remove inheritance and add all needed stuff to `FlutterRunnerParameters` directly.

**Comment by alexander-doroshko** [comment]
Not sure if `FlutterRunConfiguration` needs to extend `DartRunConfigurationBase` as well. Do you use this fact anyhow?

**Comment by alexander-doroshko** [comment]
Well, looks like you do use it as `FlutterRunner` extends `DartRunner`. Revisiting flutter run/debug code requires more time than I can spend now. Never mind.

**Comment by pq** [comment]
Thanks for the comments guys!

**Pull request merged**
