### PR TITLE
Fix open widget sample opening only counter sample app

### LINKED ISSUE #3843: "Open Widget Sample" in IntelliJ creates the Counter sample
*@johnpryan commented on Aug 30, 2019, 2:58 PM UTC:*

On the master channel, the "Open Widget Sample" feature creates the Counter sample, not the sample that was selected.

## Steps to Reproduce

1.  open the Flutter framework package in IntelliJ
2.  Navigate to src/material/chips.dart
3.  select the onDeleted widget sample and hit "Go..."

[Screen Shot 2019-08-30 at 7 49 09 AM](https://user-images.githubusercontent.com/1145719/64030591-bf80c480-cafb-11e9-81c7-32af1f920fc3.png)

4.  Observe that the sample is the counter sample, not the sample in the docs.

## Flutter doctor output

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.6-pre.57, on Mac OS X 10.14.6 18G84, locale
    en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!

```

*This issue was moved by [devoncarew](https://github.com/devoncarew) from [flutter/flutter#39571](https://github.com/flutter/flutter/issues/39571).*

### PR DESCRIPTION
**Pull request by frextrite**
now supports opening of corresponding sample

Closes #3843

### CODE REVIEW

**Comment by pq** [comment]
This looks great to me.  Thanks!

@devoncarew: can you recall why this was dropped in https://github.com/flutter/flutter-intellij/commit/81c4c61b4cb405f156229d36d32584f5fa118555#diff-9a4d2a48092af738c1fab64e45c4a34d ?  Maybe just an oversight?

**Comment by devoncarew** [comment]
> This looks great to me. Thanks!
> 
> @devoncarew: can you recall why this was dropped in [81c4c61#diff-9a4d2a48092af738c1fab64e45c4a34d](https://github.com/flutter/flutter-intellij/commit/81c4c61b4cb405f156229d36d32584f5fa118555#diff-9a4d2a48092af738c1fab64e45c4a34d) ? Maybe just an oversight?

Ah, sorry, yeah, breaking things here was _not_ intended.

**Comment by pq** [comment]
Thanks a million @frextrite!

**Comment by frextrite** [comment]
Glad to be a part of this.

**Pull request merged**
