### PR TITLE
disable xvfb to see if that fixes our bots

### PR DESCRIPTION
**Pull request by devoncarew**
- disable xvfb to see if that fixes our bots

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like our (4) `io.flutter.analytics.AnalyticsTest` tests do need xvfb installed and a `DISPLAY` variable set.

**Comment by devoncarew** [comment]
https://benlimmer.com/2019/01/14/travis-ci-xvfb/

**Comment by devoncarew** [comment]
One test failure now:

```
io.flutter.run.bazelTest.LaunchCommandsTest
    ✘ producesCorrectCommandLineForTestName (10.5s)
      junit.framework.AssertionFailedError: Not disposed java.swing.Timer: Timer (listeners: [io.flutter.perf.FlutterWidgetPerf$$Lambda$5/719860098@74da752]) (delayed for 59ms); queue:TimerQueue (javax.swing.Timer@99e471c)
```

**Comment by stevemessick** [comment]
LGTM

I restarted it. Now there is an additional failure:
```
 io.flutter.bazel.WorkspaceCacheTest
    ✘ shouldDetectConfigFileChanges
      java.lang.AssertionError: expected a workspace but it doesn't exist
          at io.flutter.bazel.WorkspaceCacheTest.checkNoConfig(WorkspaceCacheTest.java:95)
```

Tests all pass when run locally.

**Comment by devoncarew** [comment]
(re-based against master)

**Comment by devoncarew** [comment]
It's green!

**Pull request merged**
