### PR TITLE
Add constructor in widget live templates

### LINKED ISSUE #5374: Include constructor in the widget live templates
## Steps to Reproduce
A blank constructor like the following is often used to allow `const` instances.

```dart
class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    ...
  }
}
```

When creating a widget with the live templates (`stful`, `stless`, `stanim`), this constructor isn't included.
A `const` constructor is included, however, when generating a constructor with arguments as discussed in #2021, so the lack of a way to generate a blank constructor is a noticeable missing feature.

A constructor can be generated with _Code > Generate... > Constructor_, but unlike the other method, the `const` and `key` components are left out.

## Version info
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-AU)
    • Flutter version 2.0.4 at /Users/hacker1024/Library/Flutter
    • Framework revision b1395592de (3 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hacker1024/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 16+36-2231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1 RC)
    • IntelliJ at /Users/hacker1024/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.64

[✓] Connected device (3 available)
    • Mi 9T Pro (mobile) • <SERIAL> • android-arm64  • Android 11 (API 30)
    • macOS (desktop)    • macos    • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by JuYeong0413**
This pull request updates `stless`, `stful`, `stanim` live templates to include constructor. Resolves #5374 

Example for `stless`:

https://user-images.githubusercontent.com/33684401/114570964-3c50ba00-9cb1-11eb-834b-ad2188106662.mov

### CODE REVIEW

**Review by stevemessick — APPROVED** [review]

**Comment by AlexV525** [comment]
NNBD is not a default option even if you create a flutter project with Dart SDK that is higher than 2.12. From that point of view I think we use `Key key` instead.

**Comment by AlexV525** [comment]
Also #5391 .

**Comment by JuYeong0413** [comment]
Thank you @AlexV525, I've revised the files. :-)
I'll close #5391 since null safety migration for live templates is not necessary.

**Review by AlexV525 — APPROVED** [review]
LGTM. Thanks for the rapid response.

**Comment by AlexV525** [comment]
Merging since @stevemessick has already granted 10 days ago.

**Comment by mzdm** [comment]
Since Flutter 2.2, null safety is enabled by default.

https://github.com/flutter/flutter-intellij/pull/5405/commits/1a481b5b0446f8e2e97eb7f699a5cdf284c5e93e can be relanded now, right?

@AlexV525

**Comment by AlexV525** [comment]
I think yes, but still need to follow the discussion about detecting whether it's null-safety which is suggested in https://github.com/Dart-Code/Dart-Code/issues/3347#issuecomment-842174815 .

**Comment by stevemessick** [comment]
We need to wait until the analysis server is updated to provide the templates, then the plugin needs to be updated to use them. See the comment by @DanTup mentioned above.

**Comment by DanTup** [comment]
@stevemessick FYI - from the comments in https://github.com/Dart-Code/Dart-Code/issues/3347#issuecomment-844202364 I'm going to ship the null-safe versions in this months release. Moving to the server will take some time and since people are encouraged to migrate, producing no errors in that case seems most sensible in the meantime.

**Comment by stevemessick** [comment]
Ah, good point. We should make the change as well. @JuYeong0413 do you want to do that?

**Comment by AlexV525** [comment]
> Previously I have opened #5391 for migrating live templates to null safety - should I reopen this also?

There can be some improvement in this PR. I suggest to create a new one with the latest commit. :)

**Pull request merged**
