### PR TITLE
Add a TODO

### PR DESCRIPTION
**Pull request by stevemessick**
@devoncarew Add a TODO, as promised to @pq

### CODE REVIEW

**Comment by stevemessick** [comment]
I signed it!

**Comment by stevemessick** [comment]
Anyone know what's up with the `cla:no` label?

**Comment by stevemessick** [comment]
@mit-mit Something got lost and the googlebot is claiming I need to sign a CLA. First, do I need to do that? If so, individual or company?

**Comment by devoncarew** [comment]
You don't need to sign it. This generally means that the email address on your commit doesn't match what google has on file. You may want to run some variant of `git log` locally to see if the email address looks right.

**Comment by devoncarew** [comment]
If no, this may get you back on track: `git config --global user.email email@example.com`.

**Comment by mit-mit** [comment]
There was a CLAbot problem yesterday; it should have been fixed now.

**Pull request merged**
