### PR TITLE
Fix creating package project

### LINKED ISSUE #6431: At least one platform must be selected while creating flutter package
Getting **"At least one platform must be selected while creating flutter package"**

## Steps to Reproduce

- Update plugin version to `71.0.3`
- Create new package

## Version info
`71.0.3`

## Screenshot
image

### PR DESCRIPTION
**Pull request by crasowas**
Fixes #6431

### CODE REVIEW

**Review by stevemessick — APPROVED** [review]
I patched this in and built a plugin to test it. No problems.

Thanks!

**Comment by stevemessick** [comment]
Unfortunately, all commits have to be signed. See this article for more info:
https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e

**Comment by stevemessick** [comment]
Another source for signing info:
https://github.com/flutter/flutter/wiki/Signing-commits

FWIW I followed the guide I linked in my previous comment. It took a while, but once I got everything set up I'm back to my old workflow where I don't have to provide any authentication, other than being logged in to a properly-configured computer.

**Comment by crasowas** [comment]
> Unfortunately, all commits have to be signed. See this article for more info:
> https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e

I've solved it.

Thanks!

**Comment by JDongKhan** [comment]
苏宁豆芽图片20230523105440043

How to solve this version.

**Pull request merged**
