### PR TITLE
Delete user_journeys.md

### PR DESCRIPTION
**Pull request by mit-mit**
Deleting this, as this is now covered on flutter.io, and we won't want duplication

### CODE REVIEW

**Comment by mit-mit** [comment]
@devoncarew please review

**Comment by mit-mit** [comment]
@devoncarew please review

**Comment by pq** [comment]
LGTM!

**Comment by devoncarew** [comment]
This was never really meant to be user facing, but more to help us guide our developer efforts. We should reinstate this - perhaps moving it into a wiki.

**Pull request merged**
