### PR TITLE
add a hot reload checkbox

### PR DESCRIPTION
**Pull request by devoncarew**
- add a hot reload checkbox to the launch config

@pq 

screen shot 2016-11-07 at 11 03 13 pm

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Do we want to allow non-hot reload support?  When would I not want this option?

**Comment by devoncarew** [comment]
I imagine for the same reason we want it from the command-line? Are there plans to remove `--no-hot`?

**Comment by eseidelGoogle** [comment]
I'm all for simplifying our product whenever possible.  I don't know any usecase for --no-hot other than that it might be more stable than --hot at this time.

Unless there is a reason to add --no-hot to IntelliJ, I'd vote for keeping things simple as possible and just making --hot the only mode in IntelliJ.

**Comment by pq** [comment]
Code LGTM.  Neutral about the value of the checkbox for the reasons that Eric mentioned.  Don't fee strongly either way though.

**Comment by devoncarew** [comment]
I'll put this on hold and we can determine how it fits in with the run/debug UI refactor.

**Pull request closed without merging**
