### PR TITLE
More incremental work for commented out Bazel test run config.

### PR DESCRIPTION
**Pull request by jwren**
Override getSourcePosition() in BazelPositionMapper to open the correct file when a breakpoint is hit.

### CODE REVIEW

**Comment by jwren** [comment]
Not sure what you mean under test.  Lets discuss in person.

**Comment by pq** [comment]
I just mean tested (preferably unit tested).

**Comment by jwren** [comment]
Not sure yet.  Do you know if we have tests for the Flutter test run config, io.flutter.run.test?

**Comment by pq** [comment]
I don't think so but you can see how far Brian got in the `testSrc` directory.

**Pull request merged**
