### PR TITLE
Simplify getting started instructions

### PR DESCRIPTION
**Pull request by mit-mit**
Too much duplicated content, we already link to flutter.io/setup, and that now covers the IntelliJ setup piece

### CODE REVIEW

**Comment by mit-mit** [comment]
@devoncarew please review

**Comment by pq** [comment]
FWIW I'd vote to keep this duplication in.  It won't change and for folks who already have Flutter installed the flutter.io setup docs contain lots of information they don't need.

I won't fight hard though!

**Comment by devoncarew** [comment]
Let's delete this file and put some simplified getting started instructions in the main readme.md.

**Comment by devoncarew** [comment]
@mit-mit, I'll close this PR, as I think it was super-ceded by https://github.com/flutter/flutter-intellij/pull/383.

**Pull request closed without merging**
