### PR TITLE
Add panel for DevTools deep links

### PR DESCRIPTION
**Pull request by helin24**
TODOs:
- New icon?
- Move testing over? (testing this logic is pretty annoying)

Screenshot 2024-04-01 at 3 18 19 PM

### CODE REVIEW

**Comment by helin24** [comment]
@kenzieschmoll let me know if this looks reasonable. Do you have an icon that would be reasonable here? Something that's a style like notifications or device manager would be good.

**Comment by jwren** [comment]
LGTM. Yes, icon for this page as well as others should be updated but we can do this in a future PR (https://github.com/flutter/flutter-intellij/issues/6595)

**Comment by helin24** [comment]
Okay we can land this for now and I'll work on moving over testing and getting rid of similar logic in `FlutterView`.

**Comment by kenzieschmoll** [comment]
Looks good! Agree with Jaime, icon can be addressed in a follow up.

**Pull request merged**
